"""add outgoing shots

Revision ID: 4998ecaba86e
Revises: 92369ee641eb
Create Date: 2026-09-22 11:14:16.928329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4998ecaba86e'
down_revision: Union[str, Sequence[str], None] = '92369ee641eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "games",
        sa.Column(
            "outgoing_shots",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )

    op.alter_column(
        "games",
        "outgoing_shots",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'outgoing_shots')
    # ### end Alembic commands ###
