"""add received shots

Revision ID: 92369ee641eb
Revises: a273dfe6f5e5
Create Date: 2026-09-10 11:23:42.058814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92369ee641eb'
down_revision: Union[str, Sequence[str], None] = 'a273dfe6f5e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "games",
        sa.Column(
            "received_shots",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        )
    )
    op.alter_column(
        "games",
        "received_shots",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'received_shots')
    # ### end Alembic commands ###
